import React from 'react';
import { generateProcessCurlCommand, generateProcessMultipartCurl } from './lib/curls';
import { connect } from 'react-redux';

import debounceRender from 'react-debounce-render';
import { dispatchChanges, getRequestBody, getEvalscript } from './requests/parseRequest';
import store from '../../store';
import responsesSlice from '../../store/responses';
import requestSlice from '../../store/request';
import { getSHJSCode } from './lib/generateShjsRequest';
import { getSHPYCode } from './lib/generateShPyRequest';

import CommonRequestPreview from '../common/CommonRequestPreview';
import { getJSONRequestBody, sendEditedRequest } from '../../api/process/utils';
import { addWarningAlert } from '../../store/alert';

const handleParseRequest = (text) => {
  try {
    // Form data
    let s;
    if (text.includes('-F ')) {
      s = '-F ';
    } else if (text.includes('--form ')) {
      s = '--form ';
    }
    if (s) {
      const splitted = text.split(s);
      const request = splitted.find((el) => el.includes('request='));
      const evalscript = splitted.find((el) => el.includes('evalscript='));

      if (request) {
        const requestBody = getRequestBody(request);
        dispatchChanges(JSON.parse(requestBody));
      }
      if (evalscript) {
        const evalBody = getEvalscript(evalscript);
        store.dispatch(requestSlice.actions.setEvalscript(evalBody));
      }
    } else {
      const body = getRequestBody(text);
      const parsed = JSON.parse(body);
      dispatchChanges(parsed);
    }
  } catch (err) {
    console.error('Error while parsing the request', err);
    addWarningAlert(
      'Error while parsing the request, most likely invalid JSON.\n Remember that only the body of the request and the curl commands generated by the app can be parsed.',
    );
  }
};

const RequestPreview = ({ requestState, token, mapState }) => {
  return (
    <>
      <h2 className="heading-secondary mb-3">Request Preview</h2>
      <div className="form">
        <CommonRequestPreview
          options={[
            {
              name: 'curl',
              value: generateProcessCurlCommand(requestState, mapState, token),
              nonToggle: true,
            },
            {
              name: 'curl/multipart',
              value: () => generateProcessMultipartCurl(requestState, mapState, token),
              nonToggle: true,
              customCopyFunction: (text) => navigator.clipboard.writeText(text),
            },
            {
              name: 'body',
              value: () => getJSONRequestBody(requestState, mapState),
              nonToggle: true,
            },
            {
              name: 'sh-py',
              value: () => getSHPYCode(requestState, mapState),
              nonToggle: true,
            },
            {
              name: 'sh-js',
              value: () => getSHJSCode(requestState, mapState, token),
              nonToggle: true,
            },
          ]}
          canCopy
          className="process-editor"
          onParse={handleParseRequest}
          supportedParseNames={['curl', 'curl/multipart', 'body']}
          supportedSendEditedNames={['curl']}
          sendEditedRequest={(text, args) => sendEditedRequest(token, text, args)}
          onSendEdited={(response, stringRequest) => {
            const responseUrl = URL.createObjectURL(response);
            store.dispatch(
              responsesSlice.actions.setImageResponse({
                src: responseUrl,
                format: response.type,
                stringRequest,
                mode: 'PROCESS',
                displayResponse: true,
              }),
            );
          }}
          token={token}
          id="process-req-preview"
        />
      </div>
    </>
  );
};

const mapStateToProps = (store) => ({
  requestState: store.request,
  mapState: store.map,
  token: store.auth.user.access_token,
});

const debouncedComponent = debounceRender(RequestPreview, 1000);

export default connect(mapStateToProps, null)(debouncedComponent);
